fix(search): merge and aireraking are now accessible as json.RawMessage
algolia/algoliasearch-client-go pull request #719
Opened 2023-03-06 16:29 UTC by vredens

| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no     
| Related Issue     | 
| Need Doc update   | no

## Describe your change

Added two new properties to the search.QueryRes data structure (`Merge` and `AIReRanking`) so API response information under `merge` and `aiReRanking` is available.

## What problem is this fixing?

Query response data structure (`search.QueryRes`) does not include `merge` and `aiReRanking` information. This data is needed for debugging and observability related to the use of personalization and AI ReRanking.

2024-05-29 11:28 UTC, helenamariano requested changes
Looks great! Just some small changes.

2024-05-29 11:28 UTC, helenamariano commented on algolia/search/responses_search.go
> +	AIReRanking                json.RawMessage                   `json:"aiReRanking"`
```suggestion
	AIReRanking               *AIReRanking                 `json:"aiReRanking"`
```

2024-05-29 11:28 UTC, helenamariano commented on algolia/search/responses_search.go
> +	AIReRanking                json.RawMessage                   `json:"aiReRanking"`
We can directly marshal into the `AIReRanking` type

2024-05-29 11:28 UTC, helenamariano commented on algolia/search/responses_search.go
> +	Merge                      json.RawMessage                   `json:"merge"`
```suggestion
	Merge                      *Merge                  `json:"merge"`
```

2024-05-29 11:28 UTC, helenamariano commented on algolia/search/responses_search.go
> +func (r QueryRes) UnmarshalMerge(v interface{}) error {
We don't need this if we marshal directly into the object.

2024-05-29 11:42 UTC, Fluf22 commented on algolia/search/responses_merge.go
> +	Facets map[string]int
```suggestion
	Facets map[string]int `json:"facets"`
```

2024-06-07 22:12 UTC, vredens commented
All fixed. Thanks for the review @helenamariano and @Fluf22

2024-06-08 18:15 UTC, Fluf22 approved these changes
Thanks!
@helenamariano I'll let you give the final approval

2024-06-11 00:47 UTC, helenamariano approved these changes

2024-06-12 23:28 UTC, merged